# CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0 --noise_ratio 0.0 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.05 --noise_ratio 0.05 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.1 --noise_ratio 0.1 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.25 --noise_ratio 0.25 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.5 --noise_ratio 0.5 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt

CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0_v2 --noise_ratio 0.0 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.05_v2 --noise_ratio 0.05 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.1_v2 --noise_ratio 0.1 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.25_v2 --noise_ratio 0.25 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
CUDA_VISIBLE_DEVICES=4 python -m notes.online_test_noise --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir notes/depthsplat_4v_noise0.5_v2 --noise_ratio 0.5 --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
