# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene b90f2c02287490e7
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene b90f2c02287490e7
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene b90f2c02287490e7

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene ebd1ce931f852b44
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene ebd1ce931f852b44
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene ebd1ce931f852b44

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene d59b85d97234e592
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene d59b85d97234e592
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene d59b85d97234e592

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene bc69599f807f4bbe
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene bc69599f807f4bbe
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene bc69599f807f4bbe

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 6de80f26ff52ab0b
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 6de80f26ff52ab0b
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 6de80f26ff52ab0b

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 2d60837ef2e52abd
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 2d60837ef2e52abd
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 2d60837ef2e52abd
    
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 0ed25f15cbccd939
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 0ed25f15cbccd939
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 0ed25f15cbccd939

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 7a13c5debea977a8
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 7a13c5debea977a8
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 7a13c5debea977a8

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 9266d12186a3612c
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 9266d12186a3612c
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 9266d12186a3612c

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 5451cefde53f06f1
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 5451cefde53f06f1
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 5451cefde53f06f1

CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 18a86c01aaaaaa8b
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 18a86c01aaaaaa8b
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 18a86c01aaaaaa8b

CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 3e02762a89de4c7d
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 3e02762a89de4c7d
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 3e02762a89de4c7d

CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene bde72676dac5dc06
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene bde72676dac5dc06
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene bde72676dac5dc06

CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene bc70abfcfd247074
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene bc70abfcfd247074
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene bc70abfcfd247074

CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene edbb53a0f5dd688c
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene edbb53a0f5dd688c
CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_2v_0.8ind.json --out_dir supplementary/2v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene edbb53a0f5dd688c