# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene de129b4aa11af575
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene de129b4aa11af575
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene de129b4aa11af575

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene ebd1ce931f852b44
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene ebd1ce931f852b44
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene ebd1ce931f852b44

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 09b505bb829c1d12
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 09b505bb829c1d12
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 09b505bb829c1d12

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 49be5de41d619cb1
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 49be5de41d619cb1
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 49be5de41d619cb1

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene cd1d68bc375fd119
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene cd1d68bc375fd119
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene cd1d68bc375fd119

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene b4a257007abedf15
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene b4a257007abedf15
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene b4a257007abedf15
    
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 845fcf8e2d6efde7
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 845fcf8e2d6efde7
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 845fcf8e2d6efde7

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 3af70052616f7fa1
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 3af70052616f7fa1
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 3af70052616f7fa1

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene b8fda11b15ac85ff
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene b8fda11b15ac85ff
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene b8fda11b15ac85ff

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene c3ce59bd532d23f2
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene c3ce59bd532d23f2
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene c3ce59bd532d23f2

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 6f10a628fb152c0d
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 6f10a628fb152c0d
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 6f10a628fb152c0d

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene d4745b3e1bf70910
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene d4745b3e1bf70910
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene d4745b3e1bf70910

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 1961bb85524de229
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 1961bb85524de229
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 1961bb85524de229

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 473e6ec61583d90f
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 473e6ec61583d90f
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 473e6ec61583d90f

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 81c3625e4e3c76ee
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 81c3625e4e3c76ee
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 81c3625e4e3c76ee

# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene d59b85d97234e592 --cell_scale 1.0
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene d59b85d97234e592
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene d59b85d97234e592

CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model gscube --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --overfit_to_scene 3e02762a89de4c7d --cell_scale 3.0
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt --overfit_to_scene 3e02762a89de4c7d
# CUDA_VISIBLE_DEVICES=3 python -m supplementary.re10k_get_images --model depth_any --index_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k_all_4v_0.8ind.json --out_dir supplementary/4v --model_path /data2/xxy/code/depthsplat/checkpoints/depthsplat-anysplat/checkpoints/epoch_3-step_100000-v1.ckpt --overfit_to_scene 3e02762a89de4c7d