# CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/re10k_2v_indicies_expansion.json --out_dir notes/depthsplat_2v_expansion --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/re10k_4v_indicies_expansion.json --out_dir notes/depthsplat_4v_expansion --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/re10k_6v_indicies_expansion.json --out_dir notes/depthsplat_6v_expansion --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/re10k_8v_indicies_expansion.json --out_dir notes/depthsplat_8v_expansion --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/re10k_10v_indicies_expansion.json --out_dir notes/depthsplat_10v_expansion --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt
# CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model depthsplat --index_path /data2/xxy/code/depthsplat/assets/re10k_12v_indicies_expansion.json --out_dir notes/depthsplat_12v_expansion --model_path /data0/xxy/code/depthsplat/checkpoints/re10k-256x256-depthsplat-small/checkpoints/epoch_27-step_300000.ckpt



# CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model gscube --index_path /data2/xxy/code/depthsplat/assets/re10k_2v_indicies_expansion.json --out_dir notes/gscube_2v_expansion --model_path /data2/xxy/code/depthsplat/assets/evaluation_index_re10k.json --out_dir notes/gscube_2v_expansion --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt
CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model gscube --index_path /data2/xxy/code/depthsplat/assets/re10k_4v_indicies_expansion.json --out_dir notes/gscube_4v_expansion --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt --anchor_features
CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model gscube --index_path /data2/xxy/code/depthsplat/assets/re10k_6v_indicies_expansion.json --out_dir notes/gscube_6v_expansion --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt
CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model gscube --index_path /data2/xxy/code/depthsplat/assets/re10k_8v_indicies_expansion.json --out_dir notes/gscube_8v_expansion --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt
CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model gscube --index_path /data2/xxy/code/depthsplat/assets/re10k_10v_indicies_expansion.json --out_dir notes/gscube_10v_expansion --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt
CUDA_VISIBLE_DEVICES=7 python notes/online_test.py --model gscube --index_path /data2/xxy/code/depthsplat/assets/re10k_12v_indicies_expansion.json --out_dir notes/gscube_12v_expansion --model_path /data2/xxy/code/depthsplat/checkpoints/gscube-depth22-gpc1-scale4-with-skip-small-woknn-maxconf-scratch-4w/checkpoints_backups/epoch_10-step_346670.ckpt