name: unbounded

num_target_views: 4
num_context_views: 2

min_distance_between_context_views: 45
max_distance_between_context_views: 135
min_distance_to_context_views: 0
max_distance_to_context_views: 50

warm_up_steps: 0
initial_min_distance_between_context_views: 25
initial_max_distance_between_context_views: 45